---
- name: Software Development Setup
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Install packages
      become: true
      ansible.builtin.package:
        name:
          - code
          - git
          - neovim
          - tmux
        state: present

    - name: Install Flatpak packages
      become: false
      community.general.flatpak:
        name:
          - cc.arduino.IDE2
          - com.axosoft.GitKraken
          - com.mongodb.Compass
          - com.ultimaker.cura
          - org.freecad.FreeCAD
          - org.kde.kleopatra
        method: "user"
        state: present

    - name: Clone TPM
      ansible.builtin.git:
        repo: https://github.com/tmux-plugins/tpm
        dest: ~/.config/tmux/plugins/tpm
        version: master
