---
- name: Flatpak and Flatpak Apps
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Install Flatpak if not present
      become: true
      ansible.builtin.package:
        name: flatpak
        state: present

    - name: Add Flathub remote at user level if not already added
      become: false
      ansible.builtin.command:
        cmd: flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
      args:
        creates: "{{ lookup('env', 'HOME') }}/.local/share/flatpak"

    - name: Install Flatpak packages
      become: false
      community.general.flatpak:
        name:
          - com.discordapp.Discord
          - com.github.tchx84.Flatseal
          - com.google.Chrome
          - com.usebottles.bottles
          - io.github.flattool.Warehouse
          - io.gitlab.librewolf-community
          - org.remmina.Remmina
        method: "user"
        state: present
