---
- name: Setup Game Launchers
  hosts: localhost
  become: false
  connection: local
  gather_facts: false

  tasks:
    - name: Install Game Launchers via Flatpak
      community.general.flatpak:
        name:
          - com.heroicgameslauncher.hgl
          - net.davidotek.pupgui2
        method: "user"
        state: present

    - name: Install Steam via system package manager
      become: true
      ansible.builtin.package:
        name: steam
        state: present
