---
- name: Setup NVIDIA GPU Utilities and Game Launchers
  hosts: localhost
  become: false
  connection: local
  gather_facts: false

  tasks:
    - name: Install NVIDIA GPU Utilities and Game Launchers
      community.general.flatpak:
        name:
          - com.heroicgameslauncher.hgl
          - com.leinardi.gwe
          - net.davidotek.pupgui2
          - org.coolero.Coolero
        method: "user"
        state: present
