---
- name: Python Setup
  hosts: localhost
  connection: local
  gather_facts: true

  # Ensure uv is discoverable after installation by prepending ~/.local/bin to PATH
  vars:
    user_path: "{{ ansible_env.HOME }}/.local/bin:{{ ansible_env.PATH }}"
  environment:
    PATH: "{{ user_path }}"

  tasks:
    - name: Install uv
      ansible.builtin.shell: |
        curl -LsSf https://astral.sh/uv/install.sh | env INSTALLER_NO_MODIFY_PATH=1 sh
      args:
        executable: /bin/bash

    - name: Install tldr via uv
      ansible.builtin.shell: |
        uv tool install tldr
      args:
        executable: /bin/bash

    - name: Install Poetry via uv
      ansible.builtin.shell: |
        uv tool install poetry
      args:
        executable: /bin/bash
