---
- name: Sync and Storage Setup
  hosts: localhost
  become: true
  connection: local
  gather_facts: true

  tasks:
    - name: Install packages
      ansible.builtin.package:
        name:
          - syncthing
        state: present

    - name: Install rclone via official install script
      ansible.builtin.shell: |
        curl https://rclone.org/install.sh | bash
      args:
        executable: /bin/bash

    - name: Install Flatpak packages
      become: false
      community.general.flatpak:
        name:
          - com.zettlr.Zettlr
          - md.obsidian.Obsidian
          - org.cryptomator.Cryptomator
          - org.filezillaproject.Filezilla
        method: "user"
        state: present
