---
- name: Machine Setup
  hosts: localhost
  become: true
  connection: local
  gather_facts: true

  tasks:
    - name: Install packages
      ansible.builtin.package:
        name:
          - curl
          - exfatprogs
          - ratbagd
          - ripgrep
          - syncthing
          - xdg-user-dirs
        state: present

    - name: Uninstall packages
      ansible.builtin.package:
        name: firefox
        state: absent
