#!/usr/bin/env python3
import sys

content = sys.stdin.read().splitlines()

for line in content:
    print(line)

lines_to_add = [
    'source "$HOME/.config/bash/bashenv.sh"',
]

for line in lines_to_add:
    if line not in content:
        print(line)
