[diff]
command = "nvim"
args = ["-d", "{{ .Destination }}", "{{ .Target }}"]

[merge]
command = "nvim"
args = [
    "-d",
    "{{ .Target }}",
    "{{ .Source }}",
    "{{ .Destination }}",
    "-c",
    "wincmd J | set diffopt+=vertical"
]